/*
 * File: app/view/home/LogoPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DMSApp.view.home.LogoPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.homelogopanel',

    requires: [
        'DMSApp.view.home.LogoPanelViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.TextItem',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'homelogopanel'
    },
    height: 45,
    layout: 'fit',

    items: [
        {
            xtype: 'toolbar',
            style: 'background: url(./resources/images/bg.jpg)',
            items: [
                {
                    xtype: 'tbtext',
                    style: 'color:#fff;font-size:16px;',
                    text: '设备管理'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var main = button.up('main');
                        main.getLayout().setActiveItem('card-home');
                    },
                    itemId: 'homeBtn',
                    icon: './resources/icons/home24.png',
                    scale: 'medium'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var logo = button.up('homelogopanel');
                        if (!logo.userEditWin) {
                            logo.userEditWin = Ext.create('widget.homeusereditwindow');
                        }
                        logo.userEditWin.show(button);
                    },
                    itemId: 'userBtn',
                    icon: './resources/icons/woman24.png',
                    scale: 'medium'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var main = button.up('main');
                        main.getLayout().setActiveItem('card-setting');
                    },
                    itemId: 'settingBtn',
                    icon: './resources/icons/gear24.png',
                    scale: 'medium'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var main = button.up('main');
                        Ext.Msg.confirm('确认', '确定要退出当前登录吗？', function(btnId, text, opt) {
                            if ('yes'==btnId) {
                                // TODO
                                main.getLayout().setActiveItem('card-login');
                            }
                        });
                    },
                    itemId: 'logoutBtn',
                    icon: './resources/icons/power24.png',
                    scale: 'medium'
                }
            ]
        }
    ]

});