/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DMSApp.view.Main', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.main',

    requires: [
        'DMSApp.view.MainViewModel',
        'DMSApp.view.login.Panel',
        'DMSApp.view.home.Panel',
        'DMSApp.view.setting.Panel',
        'Ext.panel.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.TextItem'
    ],

    viewModel: {
        type: 'mypanel12'
    },
    layout: 'card',

    items: [
        {
            xtype: 'loginpanel',
            itemId: 'card-login'
        },
        {
            xtype: 'homepanel'
        },
        {
            xtype: 'settingpanel'
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            style: 'background: url(./resources/images/bg.jpg);',
            items: [
                {
                    xtype: 'tbtext',
                    style: 'color:#fff;',
                    text: '&copy; 2014 广州中山大学附属第一医院'
                }
            ]
        }
    ]

});