/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'Usage'
    ],
    stores: [
        'Locations',
        'Rooms',
        'Divisions',
        'Usages',
        'Users'
    ],
    views: [
        'home.device.Panel',
        'home.device.EditWindow',
        'setting.Panel',
        'home.LogoPanel',
        'home.user.EditWindow',
        'home.maintainance.TabPanel',
        'home.maintainance.ContextMenu'
    ],
    controllers: [
        'Main'
    ],
    name: 'DMSApp',

    launch: function() {
        Ext.create('DMSApp.view.MainViewport');
    }

});
