/*
 * File: app/view/home/maintainance/ContextMenu.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DMSApp.view.home.maintainance.ContextMenu', {
    extend: 'Ext.menu.Menu',
    alias: 'widget.homemaintainancecontextmenu',

    requires: [
        'DMSApp.view.home.device.ContextMenuViewModel1',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'homemaintainancecontextmenu'
    },
    width: 120,

    items: [
        {
            xtype: 'menuitem',
            handler: function(item, e) {
                var grid = item.parentMenu.grid; //console.dir(grid);
                var selMod = grid.getSelectionModel();
                if (selMod.getCount()===1) {
                    var record = selMod.getSelection()[0];
                    Ext.Ajax.request({
                        url: './resources/data/success.json',
                        params: { id: record.data.id, option: 'renew' },
                        success: function(response){
                            var text = response.responseText;
                            var obj = Ext.decode(text);
                            grid.getStore().load();
                        }
                    });
                } else {
                    Ext.Msg.alert('错误', '请选择一条记录进行操作！');
                }
            },
            itemId: 'renewItem',
            icon: './resources/icons/left16.png',
            text: '恢复'
        },
        {
            xtype: 'menuitem',
            itemId: 'nullItem',
            text: '无'
        }
    ],

    checkStatus: function(record) {
        var me = this;
        if (record.data.deviceStatus===-1) {
            me.down('#renewItem').show();
            me.down('#nullItem').hide();
        } else {
            me.down('#renewItem').hide();
            me.down('#nullItem').show();
        }
    }

});