/*
 * File: app/view/home/user/EditWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DMSApp.view.home.user.EditWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.homeusereditwindow',

    requires: [
        'DMSApp.view.home.device.EditWindowViewModel1',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Text',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'homeusereditwindow'
    },
    width: 400,
    layout: 'fit',
    closeAction: 'hide',
    title: '修改密码',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            itemId: 'editform',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'id'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '用户名',
                    name: 'username'
                },
                {
                    xtype: 'radiogroup',
                    fieldLabel: '性别',
                    items: [
                        {
                            xtype: 'radiofield',
                            name: 'sex',
                            boxLabel: '女',
                            inputValue: 'female'
                        },
                        {
                            xtype: 'radiofield',
                            name: 'male',
                            boxLabel: '男',
                            inputValue: 'sex'
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '原始密码',
                    name: 'password',
                    inputType: 'password'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '新密码',
                    name: 'password1',
                    inputType: 'password'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '再输一次',
                    name: 'password2',
                    inputType: 'password'
                },
                {
                    xtype: 'container',
                    itemId: 'buttons',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var fp = button.up('form');
                                fp.getForm().submit({
                                    clientValidation: true,
                                    url: './resources/data/success.json',
                                    params: {},
                                    success: function(form, action) {
                                        Ext.Msg.alert('成功', action.result.msg);
                                        fp.up('window').close();
                                    },
                                    failure: function(form, action) {
                                        switch (action.failureType) {
                                            case Ext.form.action.Action.CLIENT_INVALID:
                                            Ext.Msg.alert('失败', '请正确填写表单内容！');
                                            break;
                                            case Ext.form.action.Action.CONNECT_FAILURE:
                                            Ext.Msg.alert('失败', '通信错误！');
                                            break;
                                            case Ext.form.action.Action.SERVER_INVALID:
                                            Ext.Msg.alert('失败', action.result.msg);
                                        }
                                    }
                                });
                            },
                            width: 100,
                            text: '保存'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                button.up('window').close();
                            },
                            margin: '0 0 0 10',
                            text: '取消'
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        show: 'onWindowShow',
        close: 'onWindowClose'
    },

    onWindowShow: function(component, eOpts) {
        var me = this;
        var fp = me.down('form');
        Ext.Ajax.request({
            url: './resources/data/user.json',
            params: { },
            success: function(response){
                var text = response.responseText;
                var obj = Ext.decode(text);
                fp.getForm().loadRecord(Ext.create('Ext.data.Model', obj.user));
            }
        });
    },

    onWindowClose: function(panel, eOpts) {
        var me = this;
        me.down('form').getForm().reset();
    }

});