/*
 * File: app/view/login/Panel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DMSApp.view.login.Panel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.loginpanel',

    requires: [
        'DMSApp.view.login.PanelViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.event.Event'
    ],

    viewModel: {
        type: 'loginpanel'
    },
    itemId: 'card-login1',
    layout: 'absolute',
    bodyStyle: 'background: url(./resources/images/bg.jpg)',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            x: 0,
            y: 5,
            html: '临床科室设备管理系统',
            itemId: 'logo',
            bodyPadding: 5,
            bodyStyle: 'backgroud:#DCDCDC;'
        },
        {
            xtype: 'form',
            x: 50,
            y: 50,
            width: 400,
            bodyPadding: 10,
            title: '登录',
            fieldDefaults: {
                labelWidth: 75
            },
            listeners: {
                render: 'onLoginFormRender',
                afterlayout: 'onLoginFormAfterLayout'
            },
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '帐号',
                    name: 'username'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '密码',
                    name: 'password',
                    inputType: 'password',
                    enableKeyEvents: true,
                    listeners: {
                        keypress: 'onPasswordKeypress'
                    }
                },
                {
                    xtype: 'container',
                    itemId: 'buttons',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'fillct'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var me = button.up('loginpanel');
                                me.doLogin(button);
                            },
                            width: 100,
                            text: '登录'
                        }
                    ]
                }
            ]
        }
    ],

    onLoginFormRender: function(component, eOpts) {
        var me = this;//console.dir(me);
        var fp = component;
        var w = fp.getWidth();
        var h = fp.getHeight();
        var v = me.up('viewport');
        var vw = v.getWidth();
        var vh = v.getHeight();
        fp.setXY([(vw-w)*2/3, (vh-h)/2]);
    },

    onLoginFormAfterLayout: function(container, layout, eOpts) {
        var me = this;
        var fp = container;
        setTimeout(function() {
            fp.getForm().findField('username').focus();
        }, 500);
    },

    onPasswordKeypress: function(textfield, e, eOpts) {
        var me = this;
        if (e.getKey()==Ext.event.Event.ENTER) {
            me.doLogin(textfield);
        }
    },

    doLogin: function(target) {
        var me = this;
        var fp = target.up('form');
        var vp = fp.up('viewport');
        var main = me.up('main');
        main.getLayout().setActiveItem('card-home');
    }

});